version: "3.6"

services:
  app:
    image: zwilson/jobs
    build: .
    volumes:
      - ./app:/usr/src/app
      - ./configs/scrapy/scrapy.cfg:/usr/src/scrapy.cfg
      - ./items:/usr/src/items
    command: scrapyd-deploy
  scrapyd:
    image: zwilson/docker-scrapyd
    ports:
      - 6800:6800
    depends_on:
      - splash
    volumes:
      - ./items:/usr/src/items
      - ./configs/scrapyd/scrapyd.conf:/etc/scrapyd/scrapyd.conf
  splash:
    image: scrapinghub/splash
    ports:
      - 8050:8050
